###
GET http://localhost:5176/games

###
GET http://localhost:5176/games/1

###
POST http://localhost:5176/games
Content-Type: application/json

{
    "name":"My Name",  
    "genre":"My Genre",
    "price":19.99,
    "releaseDate":"2011-11-18"
}