###
GET http://localhost:5176/games

###
GET http://localhost:5176/games/4

###
POST http://localhost:5176/games
Content-Type: application/json

{
    "name":"MineCraft II",
    "genreId":2,
    "price":19.99,
    "releaseDate":"2011-11-18"
}

###
PUT http://localhost:5176/games/4
Content-Type: application/json

{
    "name":"MineCraft III",
    "genreId":2,
    "price":19.99,
    "releaseDate":"2011-11-18"
}